import React, { useState } from 'react';
import { ArrowUp, Bot, ChevronRight, Copy, Lightbulb, Plus, Send, Sparkles, Trash2, UserRound } from 'lucide-react';
import './ai-assistant.css';

const API = 'http://127.0.0.1:8787/api/v1';
const prompts = ['Avgust oyida sof foyda qancha bo‘ldi?', 'Qaysi qarzdorliklar xavfli?', 'Cash-gap bo‘yicha xulosa ber', 'Ishlab chiqarish samaradorligini tahlil qil'];

export default function AIAssistant({ dashboard }) {
  const [messages, setMessages] = useState([{ role:'assistant', text:'Assalomu alaykum. Men Biolife moliyaviy ma’lumotlari bo‘yicha yordamchiman. Daromad, xarajat, qarzdorlik, ishlab chiqarish yoki byudjet haqida savol bering.', source:'Biolife ma’lumotlar bazasi' }]);
  const [prompt, setPrompt] = useState(''); const [sending, setSending] = useState(false);
  const send = async value => { const text=(value ?? prompt).trim(); if(!text||sending)return; setPrompt(''); setMessages(m=>[...m,{role:'user',text}]); setSending(true); try { const r=await fetch(`${API}/ai/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:text})}); const data=await r.json(); setMessages(m=>[...m,{role:'assistant',text:data.answer,source:data.source}]); } catch { setMessages(m=>[...m,{role:'assistant',text:'Ma’lumotlar serveriga ulanib bo‘lmadi. API server ishlayotganini tekshiring.',source:'Tizim'}]); } finally { setSending(false); } };
  return <div className="ai-page"><div className="ai-heading"><div><span className="eyebrow">AI MOLIYAVIY TAHLILCHI</span><h1>Moliyaviy yordamchi <Sparkles size={25}/></h1><p>Raqamlarni tushuntiradi, risklarni topadi va qaror uchun qisqa xulosa beradi.</p></div><button className="outline" onClick={()=>setMessages([])}><Trash2 size={15}/> Suhbatni tozalash</button></div><div className="ai-layout"><aside className="ai-context"><div className="assistant-card"><div className="bot-orb"><Bot size={25}/></div><div><strong>Biolife Assistant</strong><span>Ma’lumotlar bazasi bilan ulangan</span></div><i/></div><div className="context-block"><span className="eyebrow">HOZIRGI KONTEKST</span><div><small>Hisobot davri</small><strong>{dashboard?.meta?.period || 'Avgust 2026'}</strong></div><div><small>Daromad</small><strong>{dashboard?.summary?.income?.value || '728.4M'}</strong></div><div><small>Sof foyda</small><strong>{dashboard?.summary?.netProfit?.value || '336.7M'}</strong></div></div><div className="prompt-list"><span className="eyebrow">TEZKOR SAVOLLAR</span>{prompts.map(p=><button key={p} onClick={()=>send(p)}>{p}<ChevronRight size={14}/></button>)}</div><div className="ai-disclaimer"><Lightbulb size={16}/><span>AI tavsiyasi moliyaviy amalni o‘zi bajarmaydi. Yakuniy tasdiq sizda qoladi.</span></div></aside><section className="chat-panel"><div className="chat-top"><div><strong>Suhbat</strong><span>Manbalar bilan izohlangan javoblar</span></div><span className="online"><i/> Online</span></div><div className="messages">{messages.map((m,i)=><div className={'message-row '+m.role} key={i}><div className="message-avatar">{m.role==='assistant'?<Bot size={16}/>:<UserRound size={16}/>}</div><div className="message"><div className="message-label">{m.role==='assistant'?'BIOLIFE ASSISTANT':'SIZ'}</div><p>{m.text}</p>{m.source&&<small>Manba: {m.source}</small>}{m.role==='assistant'&&<button className="copy-btn" onClick={()=>navigator.clipboard?.writeText(m.text)}><Copy size={13}/></button>}</div></div>)}{sending&&<div className="message-row assistant"><div className="message-avatar"><Bot size={16}/></div><div className="message typing"><span/><span/><span/></div></div>}</div><div className="prompt-area"><div className="prompt-box"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Savolingizni yozing..." rows="1"/><button className="send-btn" onClick={()=>send()} disabled={!prompt.trim()||sending}><ArrowUp size={18}/></button></div><span>Enter — yuborish · Shift + Enter — yangi qator</span></div></section></div></div>
}
